services:
  mysql:
    container_name: mysql
    image: mysql/mysql-server:8.0.28-1.2.7-server
    ports:
      - 3306:3306
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'
    networks:
      - iqs-network
    volumes:
      - ./config:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql

networks:
  iqs-network:
    driver: bridge